baseURL = 'https://samsobjectfinder.com/'
languageCode = 'en-us'
title = 'Sam's DayZ Object Finder'
theme = 'ananke'

relativeURLs = false
canonifyURLs = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderer]
unsafe = true

[params]
description = "A searchable, exportable database of every DayZ object for modders and map makers."
favicon = "favicon.png"
images = ["images/logo.png"]
